@startuml 时序图
line-[#Grey]> line : 创建
note right
    长度为7
end note
line-[#Red]> Gourd.ONE : 放在6号位
line-[#Orange]> Gourd.TWO : 放在3号位
line-[#Yellow]> Gourd.THREE : 放在1号位
line-[#Green]> Gourd.FOUR : 放在5号位
line-[#Cyan]> Gourd.FIVE : 放在2号位
line-[#Blue]> Gourd.SIX : 放在4号位
line-[#Purple]> Gourd.SEVEN : 放在0号位

theGeezer-[#Grey]> theGeezer : 创建
sorter-[#Grey]> sorter : 创建
theGeezer-[#Grey]> sorter : 设置为排序方法
theGeezer-[#Grey]> line : 排序
log-[#Grey]> theGeezer : 排序日志
writer-[#Grey]> writer : 创建新文件
note right
    文件名为"result.txt"
end note
writer-[#Grey]> log : 写入缓冲区
writer-[#Grey]> writer : 刷新缓冲流
writer-[#Grey]> writer : 关闭
@enduml